# SPDX-FileCopyrightText: 2019-2020 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2019 Anna Dai
# SPDX-FileCopyrightText: 2020 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 2.40
  max_exploration_time: 6000

supereight:
  general:
    sequence_name:              "gazebo_maze"
  map:
    size:                       512
    dim:                        51.2
    aabb_min_W:                 [-200.0, -200.0, 0.0]
    aabb_max_W:                 [ 200.0,  200.0, 80.5]
    sampling_min_W:             [-200.0, -200.0, 0.2]
    sampling_max_W:             [ 200.0,  200.0, 70.8]
    frontier_cluster_min_ratio: 0.015625
  exploration:
    delta_t:                    0.25      #åŽŸ0.25
